import globals from 'globals';
import pluginJs from '@eslint/js';
import tseslint from 'typescript-eslint';
import stylistic from '@stylistic/eslint-plugin';

export default [
  { files: ['**/*.{js,mjs,cjs,ts}'] },
  { files: ['assets/main.js'], languageOptions: { globals: globals.browser, sourceType: 'script' } },
  pluginJs.configs.all,
  ...tseslint.configs.recommended,
  stylistic.configs.customize({
    braceStyle: '1tbs',
    quoteProps: 'as-needed',
    semi: true,
  }),
  {
    rules: {
      camelcase: 'warn',
      complexity: 'off',
      curly: ['error', 'multi-line'],
      'default-case': 'off',
      'id-length': 'warn',
      'init-declarations': 'off',
      'max-depth': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-statements': 'off',
      'no-async-promise-executor': 'warn',
      'no-await-in-loop': 'off',
      'no-bitwise': 'warn',
      'no-console': 'off',
      'no-else-return': 'off',
      'no-implicit-coercion': 'off',
      'no-inline-comments': 'off',
      'no-irregular-whitespace': 'off',
      'no-lonely-if': 'off',
      'no-magic-numbers': 'off',
      'no-negated-condition': 'warn',
      'no-nested-ternary': 'off',
      'no-plusplus': 'off',
      'no-return-assign': ['error', 'always'],
      'no-ternary': 'off',
      'no-undefined': 'off',
      'no-use-before-define': ['error', { variables: false }],
      'one-var': 'off',
      'prefer-destructuring': 'warn',
      'prefer-named-capture-group': 'warn',
      'prefer-template': 'warn',
      'require-atomic-updates': 'warn',
      'require-unicode-regexp': 'off',
      'sort-imports': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
      '@typescript-eslint/no-empty-object-type': ['error', { allowObjectTypes: 'always' }],
      '@stylistic/arrow-parens': ['error', 'as-needed'],
      '@stylistic/indent': ['error', 2, { SwitchCase: 1, VariableDeclarator: 'first' }],
      '@stylistic/max-statements-per-line': ['error', { max: 2 }],
      '@stylistic/multiline-ternary': 'warn',
      '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
    },
  },
];
