import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import stylistic from '@stylistic/eslint-plugin';
import { defineConfig } from 'eslint/config';

export default defineConfig([
  {
    files: ['**/*.{js,mjs,cjs,ts,mts,cts}'],
    plugins: { js },
    extends: ['js/recommended'],
    languageOptions: { globals: globals.nodeBuiltin },
  },
  { files: ['assets/main.js'], languageOptions: { globals: globals.browser, sourceType: 'script' } },
  tseslint.configs.recommended,
  tseslint.configs.stylistic,
  stylistic.configs.customize({
    braceStyle: '1tbs',
    indent: [2, { flatTernaryExpressions: true, VariableDeclarator: 'first' }],
    quoteProps: 'as-needed',
    semi: true,
  }),
  {
    rules: {
      'accessor-pairs': 'error',
      'array-callback-return': 'error',
      'arrow-body-style': 'error',
      'block-scoped-var': 'error',
      camelcase: 'warn',
      'class-methods-use-this': 'error',
      'consistent-return': 'error',
      'consistent-this': 'error',
      curly: ['error', 'multi-line'],
      'default-case': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-notation': 'error',
      eqeqeq: 'error',
      'func-name-matching': 'error',
      'func-names': 'error',
      'func-style': 'error',
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'error',
      'id-denylist': 'error',
      'id-length': 'warn',
      'id-match': 'error',
      'logical-assignment-operators': 'error',
      'new-cap': ['error', { capIsNew: false }],
      'no-alert': 'error',
      'no-array-constructor': 'error',
      'no-async-promise-executor': 'warn',
      'no-bitwise': 'warn',
      'no-caller': 'error',
      'no-constructor-return': 'error',
      'no-div-regex': 'error',
      'no-duplicate-imports': 'error',
      'no-empty-function': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-this': 'error',
      'no-irregular-whitespace': ['error', { skipStrings: true, skipTemplates: true }],
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': ['error', { allowLoop: true, allowSwitch: true }],
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-assign': 'error',
      'no-multi-str': 'error',
      'no-negated-condition': 'warn',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-object-constructor': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'error',
      'no-promise-executor-return': 'error',
      'no-proto': 'error',
      'no-restricted-exports': 'error',
      'no-restricted-globals': 'error',
      'no-restricted-imports': 'error',
      'no-restricted-properties': 'error',
      'no-restricted-syntax': 'error',
      'no-return-assign': ['error', 'always'],
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': 'error',
      'no-sparse-arrays': 'warn',
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-underscore-dangle': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': 'error',
      'no-unreachable-loop': 'error',
      'no-unused-expressions': 'error',
      'no-use-before-define': ['error', { variables: false }],
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-void': 'error',
      'object-shorthand': 'error',
      'operator-assignment': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-destructuring': 'warn',
      'prefer-exponentiation-operator': 'error',
      'prefer-named-capture-group': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-object-has-own': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      radix: 'error',
      'require-atomic-updates': 'warn',
      'require-await': 'error',
      strict: 'error',
      'symbol-description': 'error',
      'unicode-bom': 'error',
      'valid-typeof': 'error',
      'vars-on-top': 'error',
      yoda: 'error',
      '@typescript-eslint/consistent-type-assertions': 'off',
      '@typescript-eslint/no-empty-object-type': ['error', { allowObjectTypes: 'always' }],
      '@stylistic/array-bracket-newline': ['error', 'consistent'],
      '@stylistic/array-bracket-spacing': 'error',
      '@stylistic/array-element-newline': ['error', { consistent: true, multiline: true }],
      '@stylistic/arrow-parens': ['error', 'as-needed'],
      '@stylistic/curly-newline': 'error',
      '@stylistic/function-call-argument-newline': ['error', 'consistent'],
      '@stylistic/function-call-spacing': 'error',
      '@stylistic/function-paren-newline': 'error',
      '@stylistic/implicit-arrow-linebreak': 'error',
      '@stylistic/lines-around-comment': ['error', { afterHashbangComment: true, allowArrayEnd: true, allowArrayStart: true, allowBlockEnd: true, allowBlockStart: true, allowClassEnd: true, allowClassStart: true, allowEnumEnd: true, allowEnumStart: true, allowInterfaceEnd: true, allowInterfaceStart: true, allowModuleEnd: true, allowModuleStart: true, allowObjectEnd: true, allowObjectStart: true, allowTypeEnd: true, allowTypeStart: true, beforeLineComment: true }],
      '@stylistic/max-statements-per-line': ['error', { max: 2 }],
      '@stylistic/multiline-ternary': 'warn',
      '@stylistic/no-extra-semi': 'error',
      '@stylistic/nonblock-statement-body-position': 'error',
      '@stylistic/object-curly-newline': 'error',
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
      '@stylistic/semi-style': 'error',
      '@stylistic/switch-colon-spacing': 'error',
    },
  },
]);
